In [6]:
from scipy.stats import ortho_group
from scipy.sparse import csc_matrix, diags
from scipy.sparse.linalg import svds
import numpy as np
rng = np.random.default_rng()
orthogonal = csc_matrix(ortho_group.rvs(10, random_state=rng))
s = [0.0001, 0.001, 3, 4, 5]  # singular values
u = orthogonal[:, :5]         # left singular vectors
vT = orthogonal[:, 5:].T      # right singular vectors
A = u @ diags(s) @ vT

In [7]:
u2, s2, vT2 = svds(A, k=3)
A2 = u2 @ np.diag(s2) @ vT2
np.allclose(A2, A.toarray(), atol=1e-3)

True

In [8]:
u2

array([[-0.07145657,  0.03690721, -0.26427308],
       [-0.50913266, -0.13758191,  0.37383002],
       [-0.03830479,  0.44229136,  0.32752808],
       [-0.43535273, -0.12122557,  0.09023338],
       [-0.01540248,  0.06294428,  0.36591509],
       [-0.49722014,  0.22220673, -0.08420368],
       [ 0.14140839, -0.42586518,  0.65574284],
       [ 0.40720341,  0.31345567,  0.26846334],
       [-0.18375366,  0.62891138,  0.16914415],
       [-0.27863447, -0.20225937, -0.05769794]])

In [9]:
s2

array([3., 4., 5.])

In [10]:
np.diag(s2)

array([[3., 0., 0.],
       [0., 4., 0.],
       [0., 0., 5.]])